### ISSUE TITLE
F* explodes on ill-typed code (Impossible: Typ_unknown)

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#186]
The following code is a simplified version of a bug Simon and Enrico have been experiencing:
```
type valid : int -> Type =
  | VForall     : #p:(int -> Tot int) -> (* non-inferrable *)
                  f: (x:int -> Tot (valid (p x))) ->
                  valid 42

val hoare_consequence : valid 42 -> Tot unit
let hoare_consequence v =
  let VForall #p fpp' = v in (* #p here doesn't change anything *)
(*  ignore (fpp' 75) -- this causes bogus "patterns are incomplete" *)
  assert (is_VForall (fpp' 75))
    (* BUG: this makes F* explode: Impossible: Typ_unknown *)
```
Note that the application `fpp' h` is ill-typed. Still, the way this fails is not very nice. In particular, it seems this already passed type-checking and is already being sent to the solver, which is scary.
```
$ fstar --fstar_home ../.. bug186.fst --trace_error

Unexpected error
(unknown(0,0-0,0)) Impossible: Typ_unknown
<UNKNOWN>
<UNKNOWN>

   at Microsoft.FStar.ToSMT.Encode.encode_typ_term(syntax`2 t, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 577
   at Microsoft.FStar.ToSMT.Encode.encode_typ_pred'(FSharpOption`1 fuel_opt, syntax`2 t, env_t env, term e) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 437
   at Microsoft.FStar.ToSMT.Encode.doit@459(env_t env, FSharpList`1 binders, syntax`2 res) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 468
   at Microsoft.FStar.ToSMT.Encode.encode_typ_term(syntax`2 t, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 479
   at Microsoft.FStar.ToSMT.Encode.encode_typ_pred'(FSharpOption`1 fuel_opt, syntax`2 t, env_t env, term e) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 437
   at Microsoft.FStar.ToSMT.Encode.encode_exp(syntax`2 e, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 635
   at Microsoft.FStar.ToSMT.Encode.encode_partial_app@655(env_t env, syntax`2 e, syntax`2 head, FSharpList`1 args_e, FSharpList`1 vars, FSharpList`1 decls, FSharpList`1 args, FSharpOption`1 ht_opt) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 656
   at Microsoft.FStar.ToSMT.Encode.encode_exp(syntax`2 e, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 687
   at Microsoft.FStar.ToSMT.Encode.encode_args@799-1.Invoke(Tuple`2 tupledArg) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 801
   at Microsoft.FSharp.Collections.ListModule.loop@142-20[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list)
   at Microsoft.FStar.ToSMT.Encode.encode_args(FSharpList`1 l, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 799
   at Microsoft.FStar.ToSMT.Encode.encode_exp(syntax`2 e, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 582
   at Microsoft.FStar.ToSMT.Encode.encode_args@799-1.Invoke(Tuple`2 tupledArg) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 801
   at Microsoft.FSharp.Collections.ListModule.loop@142-20[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list)
   at Microsoft.FStar.ToSMT.Encode.encode_args(FSharpList`1 l, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 799
   at Microsoft.FStar.ToSMT.Encode.encode_typ_term(syntax`2 t, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 530
   at Microsoft.FStar.ToSMT.Encode.encode_args@799-1.Invoke(Tuple`2 tupledArg) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 800
   at Microsoft.FSharp.Collections.ListModule.loop@142-20[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list)
   at Microsoft.FStar.ToSMT.Encode.encode_args(FSharpList`1 l, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 799
   at Microsoft.FStar.ToSMT.Encode.encode_exp(syntax`2 e, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 582
   at Microsoft.FStar.ToSMT.Encode.encode_exp(syntax`2 e, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 697
   at Microsoft.FStar.ToSMT.Encode.encode_exp@712-3.Invoke(Tuple`3 tupledArg) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 723
   at Microsoft.FStar.ToSMT.Encode.encode_exp(syntax`2 e, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 710
   at Microsoft.FStar.ToSMT.Encode.encode_exp(syntax`2 e, env_t env) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 698
   at Microsoft.FStar.ToSMT.Encode.encode_sigelt'(env_t env, sigelt se) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 1481
   at Microsoft.FStar.ToSMT.Encode.encode_sigelt(env_t env, sigelt se) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 1118
   at Microsoft.FStar.ToSMT.Encode.encode_sig(env tcenv, sigelt se) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 1653
   at Microsoft.FStar.ToSMT.Encode.solver@1749-4.Invoke(env tcenv, sigelt se) in C:\Users\hritcu\Desktop\FStar\src\tosmt\encode.fs:line 1749
   at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FStar.Tc.Tc.tc_decls@1573-1.Invoke(sigelt se) in C:\Users\hritcu\Desktop\FStar\src\tc\tc.fs:line 1588
   at Microsoft.FSharp.Collections.ListModule.loop@142-20[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list)
   at Microsoft.FStar.Tc.Tc.tc_decls(Boolean for_export, env env, FSharpList`1 ses, Boolean deserialized) in C:\Users\hritcu\Desktop\FStar\src\tc\tc.fs:line 1573
   at Microsoft.FStar.Tc.Tc.tc_modul(env env, modul modul) in C:\Users\hritcu\Desktop\FStar\src\tc\tc.fs:line 1630
   at Microsoft.FStar.Tc.Tc.check_modules$cont@1667(solver_t s, modul m, env env, Unit unitVar) in C:\Users\hritcu\Desktop\FStar\src\tc\tc.fs:line 1670
   at Microsoft.FStar.Tc.Tc.check_modules@1657-1.Invoke(modul m) in C:\Users\hritcu\Desktop\FStar\src\tc\tc.fs:line 1667
   at Microsoft.FSharp.Collections.ListModule.loop@142-20[T,TState](FSharpFunc`3 f, TState s, FSharpList`1 xs)
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list)
   at Microsoft.FStar.Tc.Tc.check_modules(solver_t s, FSharpList`1 mods) in C:\Users\hritcu\Desktop\FStar\src\tc\tc.fs:line 1655
   at Microsoft.FStar.FStar.go$cont@53(FSharpList`1 filenames, Unit unitVar) in C:\Users\hritcu\Desktop\FStar\src\fstar.fs:line 56
   at <StartupCode$FStar>.$Microsoft.FStar.FStar.main@() in C:\Users\hritcu\Desktop\FStar\src\fstar.fs:line 96
```

**Comment by catalin-hritcu** [comment]
Simon is encountering a similar blow-up in a call from an STLC substitution to weakening. The example is only partially minimized. The error message/trace is this:
```
mono ../../bin/fstar.exe --fstar_home ../..  ../../lib/classical.fst stlc_strong_db_parsubst.fst --max_fuel 1 --max_ifuel 1 --trace_error

Unexpected error
(unknown(0,0-0,0)) Impossible: Typ_unknown
<UNKNOWN>
<UNKNOWN>

  at Microsoft.FStar.ToSMT.Encode.encode_typ_term (Microsoft.FStar.Absyn.syntax`2 t, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_typ_pred' (Microsoft.FSharp.Core.FSharpOption`1 fuel_opt, Microsoft.FStar.Absyn.syntax`2 t, Microsoft.FStar.ToSMT.env_t env, Microsoft.FStar.ToSMT.term e) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.doit@459 (Microsoft.FStar.ToSMT.env_t env, Microsoft.FSharp.Collections.FSharpList`1 binders, Microsoft.FStar.Absyn.syntax`2 res) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_typ_term (Microsoft.FStar.Absyn.syntax`2 t, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_typ_pred' (Microsoft.FSharp.Core.FSharpOption`1 fuel_opt, Microsoft.FStar.Absyn.syntax`2 t, Microsoft.FStar.ToSMT.env_t env, Microsoft.FStar.ToSMT.term e) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_exp (Microsoft.FStar.Absyn.syntax`2 e, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_partial_app@655 (Microsoft.FStar.ToSMT.env_t env, Microsoft.FStar.Absyn.syntax`2 e, Microsoft.FStar.Absyn.syntax`2 head, Microsoft.FSharp.Collections.FSharpList`1 args_e, Microsoft.FSharp.Collections.FSharpList`1 vars, Microsoft.FSharp.Collections.FSharpList`1 decls, Microsoft.FSharp.Collections.FSharpList`1 args, Microsoft.FSharp.Core.FSharpOption`1 ht_opt) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_exp (Microsoft.FStar.Absyn.syntax`2 e, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode+encode_args@799-1.Invoke (System.Tuple`2 tupledArg) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Adapt@3006[System.Tuple`3[Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.Util+either`2[Microsoft.FStar.ToSMT.Term+term,Microsoft.FStar.ToSMT.Term+term]],Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`2[System.Tuple`2[System.String,Microsoft.FStar.ToSMT.Term+sort],Microsoft.FStar.ToSMT.Term+term]],Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl]],System.Tuple`2[Microsoft.FStar.Util+either`2[Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]],Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+exp',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]]]],Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FStar.Absyn.Syntax+arg_qualifier]],System.Tuple`3[Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.Util+either`2[Microsoft.FStar.ToSMT.Term+term,Microsoft.FStar.ToSMT.Term+term]],Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`2[System.Tuple`2[System.String,Microsoft.FStar.ToSMT.Term+sort],Microsoft.FStar.ToSMT.Term+term]],Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl]]].Invoke (System.Tuple`3 , System.Tuple`2 ) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.ListModule.loop@144-20[Tuple`2,Tuple`3] (Microsoft.FSharp.Core.FSharpFunc`3 f, System.Tuple`3 s, Microsoft.FSharp.Collections.FSharpList`1 xs) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.ListModule.Fold[Tuple`2,Tuple`3] (Microsoft.FSharp.Core.FSharpFunc`2 folder, System.Tuple`3 state, Microsoft.FSharp.Collections.FSharpList`1 list) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_args (Microsoft.FSharp.Collections.FSharpList`1 l, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_exp (Microsoft.FStar.Absyn.syntax`2 e, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_exp (Microsoft.FStar.Absyn.syntax`2 e, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_exp (Microsoft.FStar.Absyn.syntax`2 e, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_exp (Microsoft.FStar.Absyn.syntax`2 e, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode+encode_exp@712-3.Invoke (System.Tuple`3 tupledArg) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Adapt@3006[System.Tuple`2[Microsoft.FStar.ToSMT.Encode+env_t,Microsoft.FStar.ToSMT.Encode+pattern],System.Tuple`3[Microsoft.FStar.ToSMT.Term+term,Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`2[System.Tuple`2[System.String,Microsoft.FStar.ToSMT.Term+sort],Microsoft.FStar.ToSMT.Term+term]],Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl]],System.Tuple`3[Microsoft.FStar.ToSMT.Term+term,Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`2[System.Tuple`2[System.String,Microsoft.FStar.ToSMT.Term+sort],Microsoft.FStar.ToSMT.Term+term]],Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl]]].Invoke (System.Tuple`2 , System.Tuple`3 ) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.ListModule.FoldBack[Tuple`2,Tuple`3] (Microsoft.FSharp.Core.FSharpFunc`2 folder, Microsoft.FSharp.Collections.FSharpList`1 list, System.Tuple`3 state) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode+encode_exp@710-1.Invoke (System.Tuple`3 tupledArg) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Adapt@3006[System.Tuple`3[Microsoft.FStar.Absyn.Syntax+withinfo_t`2[Microsoft.FStar.Absyn.Syntax+pat',Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FStar.Util+either`2[Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit],Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]]]]],Microsoft.FSharp.Core.FSharpOption`1[Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+exp',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]]]],Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+exp',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]]]],System.Tuple`3[Microsoft.FStar.ToSMT.Term+term,Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`2[System.Tuple`2[System.String,Microsoft.FStar.ToSMT.Term+sort],Microsoft.FStar.ToSMT.Term+term]],Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl]],System.Tuple`3[Microsoft.FStar.ToSMT.Term+term,Microsoft.FSharp.Collections.FSharpList`1[System.Tuple`2[System.Tuple`2[System.String,Microsoft.FStar.ToSMT.Term+sort],Microsoft.FStar.ToSMT.Term+term]],Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl]]].Invoke (System.Tuple`3 , System.Tuple`3 ) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.ListModule.FoldBack[Tuple`3,Tuple`3] (Microsoft.FSharp.Core.FSharpFunc`2 folder, Microsoft.FSharp.Collections.FSharpList`1 list, System.Tuple`3 state) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_exp (Microsoft.FStar.Absyn.syntax`2 e, Microsoft.FStar.ToSMT.env_t env) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_one_binding@1446[term,either`2,syntax`2] (System.Tuple`2 fuel, Microsoft.FStar.ToSMT.term fuel_tm, Microsoft.FStar.ToSMT.env_t env, Microsoft.FStar.ToSMT.env_t env0, Microsoft.FStar.Absyn.LongIdent flid, System.String f, Microsoft.FStar.ToSMT.term ftok, System.String g, System.String gtok, Microsoft.FStar.Absyn.syntax`2 t_norm, Microsoft.FStar.either`2 _arg11, Microsoft.FStar.Absyn.syntax`2 _arg12, Microsoft.FStar.Absyn.syntax`2 e) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode+encode_sigelt'@1472-11.Invoke (System.Tuple`3 tupledArg) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Core.OptimizedClosures+Adapt@3006[System.Tuple`3[Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl],Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl],Microsoft.FStar.ToSMT.Encode+env_t],System.Tuple`3[System.Tuple`5[Microsoft.FStar.Absyn.Syntax+LongIdent,System.String,Microsoft.FStar.ToSMT.Term+term,System.String,System.String],Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]],System.Tuple`3[Microsoft.FStar.Util+either`2[Microsoft.FStar.Absyn.Syntax+bvdef`1[Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+exp',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]]]],Microsoft.FStar.Absyn.Syntax+LongIdent],Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]],Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+exp',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+typ',Microsoft.FStar.Absyn.Syntax+syntax`2[Microsoft.FStar.Absyn.Syntax+knd',Microsoft.FSharp.Core.Unit]]]]],System.Tuple`3[Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl],Microsoft.FSharp.Collections.FSharpList`1[Microsoft.FStar.ToSMT.Term+decl],Microsoft.FStar.ToSMT.Encode+env_t]].Invoke (System.Tuple`3 , System.Tuple`3 ) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.ListModule.loop@144-20[Tuple`3,Tuple`3] (Microsoft.FSharp.Core.FSharpFunc`3 f, System.Tuple`3 s, Microsoft.FSharp.Collections.FSharpList`1 xs) [0x00000] in <filename unknown>:0 
  at Microsoft.FSharp.Collections.ListModule.Fold[Tuple`3,Tuple`3] (Microsoft.FSharp.Core.FSharpFunc`2 folder, System.Tuple`3 state, Microsoft.FSharp.Collections.FSharpList`1 list) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.ToSMT.Encode.encode_sigelt' (Microsoft.FStar.ToSMT.env_t env, Microsoft.FStar.Absyn.sigelt se) [0x00000] in <filename unknown>:0 
```
