### ISSUE TITLE
F* doesn't build right on Linux with F# 4.0

### ISSUE THREAD

**Issue by catalin-hritcu** [FStarLang/FStar#308]
F* doesn't build right on Linux [and Cygwin] with the newly released F# 4.0. The build seems to work (although with some warnings):
```
[hritcu@detained pub]$ make -C src      
make: Entering directory '/home/hritcu/Projects/fstar/pub/src'
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/basic.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll  basic/prims-fake.fs basic/profiling.fs basic/util.fsi basic/util.fs basic/bytes.fsi basic/bytes.fs basic/range.fsi basic/range.fs basic/getoptsimple.fsi basic/getoptsimple.fs basic/platform.fsi basic/platform.fs basic/options.fs basic/unionfind.fsi basic/unionfind.fs
fsharpc --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/format.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll  format/format.fsi format/format.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/absyn.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll absyn/syntax.fs absyn/const.fs absyn/visit.fs absyn/util.fs absyn/print.fs absyn/ssyntax.fs

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(104,32): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(105,28): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(216,57): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(216,91): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(216,125): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(217,53): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(219,78): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(219,115): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(221,36): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(221,103): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(223,63): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(380,40): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(380,106): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/absyn/print.fs(382,67): warning FS0044: This construct is deprecated. please use List.item
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/tc.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll tc/tcenv.fsi tc/tcenv.fs tc/recheck.fs tc/normalize.fsi tc/normalize.fs tc/errors.fs tc/rel.fsi tc/rel.fs tc/tcutil.fsi tc/tcutil.fs tc/tc.fs

/home/hritcu/Projects/fstar/pub/src/tc/tcenv.fs(385,24): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tc/rel.fs(1546,18): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tc/rel.fs(1572,30): warning FS0044: This construct is deprecated. please use List.item
fsharpc --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/backend.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/format.dll -r ../bin/tc.dll backend/nameenv.fsi backend/nameenv.fs backend/ml-syntax.fs backend/ocaml-codegen.fsi backend/ocaml-codegen.fs backend/ocaml-asttrans.fsi backend/ocaml-asttrans.fs

/home/hritcu/Projects/fstar/pub/src/backend/ocaml-asttrans.fs(624,25): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[]' may indicate a case not covered by the pattern(s).
fsharpc --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/extraction.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/format.dll -r ../bin/tc.dll extraction/ml-syntax.fs extraction/env.fs extraction/util.fs extraction/ocaml-codegen.fsi extraction/ocaml-codegen.fs extraction/extracttyp.fs extraction/extractexp.fs extraction/extractmod.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/parser.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/tc.dll parser/ast.fs parser/parseutil.fs parser/parse.fs parser/lexhelp.fs parser/lex.fs parser/dsenv.fsi parser/dsenv.fs parser/desugar.fsi parser/desugar.fs parser/parseit.fsi parser/parseit.fs parser/driver.fs
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -a -o ../bin/tosmt.dll -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/absyn.dll -r ../bin/tc.dll tosmt/term.fsi tosmt/term.fs tosmt/z3.fs tosmt/splitcases.fs tosmt/encode.fs

/home/hritcu/Projects/fstar/pub/src/tosmt/term.fs(274,16): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tosmt/term.fs(366,9): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tosmt/term.fs(388,13): warning FS0025: Incomplete pattern matches on this expression. For example, the value '[]' may indicate a case not covered by the pattern(s).

/home/hritcu/Projects/fstar/pub/src/tosmt/encode.fs(54,24): warning FS0044: This construct is deprecated. please use List.item

/home/hritcu/Projects/fstar/pub/src/tosmt/encode.fs(2027,17): warning FS0025: Incomplete pattern matches on this expression. For example, the value 'Caption (_)' may indicate a case not covered by the pattern(s). However, a pattern rule with a 'when' clause might successfully match this value.
fsharpc  --optimize+ --debug:full --nologo -g -O --mlcompatibility  -o ../bin/fstar-mono.exe -r System.Runtime.Serialization.dll -r System.Xml.dll -r ../bin/FSharp.PowerPack.dll -r ../bin/FSharp.PowerPack.Compatibility.dll -r ../bin/FSharp.PPrint.dll -r ../bin/basic.dll -r ../bin/format.dll -r ../bin/absyn.dll -r ../bin/backend.dll -r ../bin/extraction.dll -r ../bin/parser.dll -r ../bin/tc.dll -r ../bin/tosmt.dll fstar.fs main.fs
cp ../bin/fstar-mono.sh ../bin/fstar.exe
make: Leaving directory '/home/hritcu/Projects/fstar/pub/src'
```
The obtained `fstar.exe` binary doesn't work well though:
```
[hritcu@detained pub]$ bin/fstar.exe empty.fst 

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
An exception was thrown by the type initializer for <StartupCode$tosmt>.$Microsoft.FStar.ToSMT.Encode

[hritcu@detained pub]$ bin/fstar.exe empty.fst --trace_error              

Unexpected error
An exception was thrown by the type initializer for <StartupCode$tosmt>.$Microsoft.FStar.ToSMT.Encode
  at Microsoft.FStar.FStar.tc_prims () [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.FStar.batch_mode_tc (Microsoft.FSharp.Collections.FSharpList`1 filenames) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.FStar.go[Unit] (Microsoft.FSharp.Core.Unit _arg1) [0x00000] in <filename unknown>:0 
  at Microsoft.FStar.FStar.main[Object] () [0x00000] in <filename unknown>:0 

[hritcu@detained pub]$ z3 --version
Z3 version 4.3.2
```
Did anyone try F# 4.0 on Windows?

**Comment by catalin-hritcu** [comment]
Tried to reproduce this on Windows, but then run into this problem:
https://plus.google.com/+SteveGilham/posts/hYp7ujeA9eX

**Comment by dungpa** [comment]
@catalin-hritcu To fix that issue on Windows, you need to install Microsoft Build Tools 2015. See https://github.com/fsharp/fsfoundation/issues/470.

AFAIK F# 4.0 hasn't been released on Mono yet. What's your F# and Mono version on Linux?

**Comment by catalin-hritcu** [comment]
> To fix that issue on Windows, you need to install Microsoft Build Tools 2015. See fsharp/fsfoundation#470.

@dungpa  This indeed fixed the F# 4.0 installation issue on Windows, thank you. I've tried using F# 4.0 to build F* on Windows from Cygwin and the problem seems the same as on Linux:
```
hritcu@W7-VBox /cygdrive/c/Users/hritcu/Desktop/FStar
$ bin/fstar.exe empty.fst

Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
The type initializer for '<StartupCode$tosmt>.$Microsoft.FStar.ToSMT.Encode' threw an exception.

$ bin/fstar.exe empty.fst --trace_error

Unexpected error
The type initializer for '<StartupCode$tosmt>.$Microsoft.FStar.ToSMT.Encode' threw an exception.
   at Microsoft.FStar.ToSMT.Encode.get_solver()
   at Microsoft.FStar.FStar.tc_prims() in C:\Users\hritcu\Desktop\FStar\src\fstar.fs:line 40
   at Microsoft.FStar.FStar.batch_mode_tc(FSharpList`1 filenames) in C:\Users\hritcu\Desktop\FStar\src\fstar.fs:line 206
   at Microsoft.FStar.FStar.go[a](a _arg1) in C:\Users\hritcu\Desktop\FStar\src\fstar.fs:line 276
   at Microsoft.FStar.FStar.main[a]() in C:\Users\hritcu\Desktop\FStar\src\fstar.fs:line 288

```
I'll try to also reproduce this from VS, but for that I need to (at least locally) update the projects to use F# 4.0. Any idea how to do this easily?

> AFAIK F# 4.0 hasn't been released on Mono yet. What's your F# and Mono version on Linux?

mono 4.0.2 and F# 4.0.0.3 (build from the source release here without any problem: https://github.com/fsharp/fsharp/releases)
```
[hritcu@detained pub]$ fsharpc       
F# Compiler for F# 4.0 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

error FS0207: No inputs specified

[hritcu@detained pub]$ mono --version                                     
Mono JIT compiler version 4.0.2 (Stable 4.0.2.5/c99aa0c Mon Jul 13 18:57:35 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

**Comment by latkin** [comment]
@catalin-hritcu if you open your existing fsproj files in VS 2015, they will be compiled with the F# 4.0 compiler.  In project properties you can also toggle the FSharp.Core version you use to be 4.4.0.0, the F# 4.0 version.

![image](https://cloud.githubusercontent.com/assets/5943573/9202986/4ff3b77a-4009-11e5-83fb-0457a3a00dc6.png)

If you come across something that seems to be a sure compiler/runtime issue, please log the details at https://github.com/microsoft/visualfsharp/

**Comment by catalin-hritcu** [comment]
@latkin  Thanks a lot for the hint. I've tried with my VS 2013 and I don't get F# 4.0 in that list even for a completely fresh project:
<img width="960" alt="untitled1" src="https://cloud.githubusercontent.com/assets/5850655/9208978/0a9e4b02-4029-11e5-86d0-1b02aa72abff.png">
... and for the F* projects it's actually even worse, that list is completely disabled:
<img width="960" alt="untitled3" src="https://cloud.githubusercontent.com/assets/5850655/9208989/1b2d87d0-4029-11e5-921f-e97e5b9c2c12.png">
And idea how to fix or work around this?

**Comment by latkin** [comment]
@catalin-hritcu you need VS 2015 to have F# 4.0 easily accessible from the IDE.  If you have the F# 4.0 package + VS 2013 it's possible to hack around build targets and force 2013 to use the 4.0 compiler, but it's not a great solution.

See this SO post: http://stackoverflow.com/questions/31631691/target-f-runtime-grayed-out-why/  If your project file has been incorrectly modified (perhaps by nuget packages) it will prevent the toggle from appearing.  It's not too hard to get it back, though.

**Comment by s-zanella** [comment]
I just tried and couldn't reproduce this on Mac OS X with up-to-date versions of Mono and F# 4.0. If I remember well, this used to be reproducible on Mac OS X too.

I used a binary Mono installer and yesterday's [F# 4.0.1 release](https://github.com/fsharp/fsharp/releases/tag/4.0.1.0).

```
$ fsharpc
F# Compiler for F# 4.0 (Open Source Edition)
```
```
$ mono -V
Mono JIT compiler version 4.2.1 (explicit/6dd2d0d Tue Nov 10 18:01:18 EST 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-(detached/a173357)
	GC:            sgen
```
@catalin-hritcu can you try to update Mono/F# and confirm that this is still an open problem on Linux?

**Comment by catalin-hritcu** [comment]
Yes, I can confirm that F# 4.0.1.0 works for me too. This seems fixed. I'll update the documentation.
