### ISSUE TITLE
How to build the "tutorial" document?

### ISSUE THREAD

**Issue by master-q** [FStarLang/FStar#562]
How to build the "tutorial" document? I would like to translate the document into Japanese.

Now building it causes following error:

```
$ npm install madoko -g
$ which madoko
/usr/local/bin/madoko
$ pwd
/home/kiwamu/src/FStar/doc/tutorial
$ make
madoko -v tutorial.mdk
process: tutorial.mdk -> out/tutorial.html

  tutorial: rendering math.
process: /usr/local/bin/madoko.mdk -> out/madoko.html
error: unable to read: /usr/local/bin/madoko.mdk
  tutorial: running xelatex on math... (plain -> xdv -> svg)
  tutorial: generating math images...  (plain) (1-5)
  tutorial: analyse and embed math images.
  error: cannot read: out/math/tutorial-math-plain-1.svg
fs.js:681
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename 'out/math/tutorial-math-plain-1.svg' -> 'out/math/math-c6a6eb61fd9c6c913da73b3642ca147d.svg'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
    at $renameSync (/usr/local/lib/node_modules/madoko/lib/storage.js:41:55)
    at xrename (/usr/local/lib/node_modules/madoko/lib/storage.js:250:10)
    at Object.rename (/usr/local/lib/node_modules/madoko/lib/storage.js:255:10)
    at dimLine (/usr/local/lib/node_modules/madoko/lib/mathStaticRun.js:171:26)
    at /usr/local/lib/node_modules/madoko/lib/mathStaticRun.js:188:137
    at /usr/local/lib/node_modules/madoko/lib/std_core.js:1266:102
    at mapIter (/usr/local/lib/node_modules/madoko/lib/std_core.js:1173:21)
    at mapIter (/usr/local/lib/node_modules/madoko/lib/std_core.js:1173:49)
Makefile:5: recipe for target 'tutorial.html' failed
make: *** [tutorial.html] Error 1
$ ls out
ellipse.sty  longfbox.sty  math/        tutorial-math-full.tex   tutorial-math-plain.dim  tutorial-math-plain.tex  tutorial.html
longbox.sty  madoko2.sty   options.sty  tutorial-math-plain.aux  tutorial-math-plain.log  tutorial-math-plain.xdv
```

Is it madoko side problem?

**Comment by nikswamy** [comment]
@daanx: Any ideas?

**Comment by beurdouche** [comment]
I just tried to build the tutorial and I had no trouble.
I am using madoko version 1.0.1

**Comment by master-q** [comment]
Thanks. I'm also using madoko version 1.0.1.
I'll try to fix it by my self...

**Comment by moaazsidat** [comment]
@master-q How were you able to fix the issue? Trying to use madoko and facing a similar issue.

**Comment by master-q** [comment]
@moaazsidat Sorry. I escape from this problem with following:

```
madoko -v --png tutorial.mdk
```

Original Makefile has following, that is not used by me:

```
madoko -v tutorial.mdk
```
